version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-sqs-lambda-py"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pe5ijik88840"
s3_prefix = "sam-sqs-lambda-py"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
